export const today = [
 { "name": "Event 1",
   "who": "E-Club",
   "what": "description goes here description goes here description goes here",
   "when": "1:00",
   "where": "Ehub",
   "RSVP required": "yes",
 },
 { "name": "Event 2",
   "who": "Club 2",
   "what": "description goes here",
   "when": "2:00",
   "where": "Location 2",
   "RSVP required": "no",
 },
];

export const tomorrow = [
 { "name": "Event 3",
   "who": "Club 3",
   "what": "description goes here",
   "when": "3:00",
   "where": "Location 3",
   "RSVP required": "no",
 },
 { "name": "Event 4",
   "who": "Club 4",
   "what": "description goes here",
   "when": "4:00",
   "where": "Location 4",
   "RSVP required": "no",
 },
 { "name": "Event 5",
   "who": "Club 5",
   "what": "description goes here",
   "when": "5:00",
   "where": "Location 5",
   "RSVP required": "no",
 },
];
